version: '3'
services:
  postgres:
      image: postgres:11-alpine
      ports: 
        - 45533:5432
      environment:
        POSTGRES_DB: dev_mem
        POSTGRES_USER: dev
        POSTGRES_PASSWORD: dev